package postgres

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/music-app/recommendation-service/internal/domain/entity"
	"github.com/music-app/recommendation-service/internal/domain/repository"
)

type trackRepository struct {
	db *pgxpool.Pool
}

func NewTrackRepository(db *pgxpool.Pool) repository.TrackRepository {
	return &trackRepository{db: db}
}

func (r *trackRepository) GetByID(ctx context.Context, id string) (*entity.Track, error) {
	row := r.db.QueryRow(ctx,
		`SELECT id, spotify_id, name, artists, album, genre, duration_ms, popularity,
		        valence, energy, danceability, tempo, acousticness, instrumentalness, loudness, speechiness,
		        COALESCE(preview_url, '')
		 FROM tracks WHERE id = $1`, id)
	t, err := scanTrack(row)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	return t, err
}

func (r *trackRepository) GetBySpotifyID(ctx context.Context, spotifyID string) (*entity.Track, error) {
	row := r.db.QueryRow(ctx,
		`SELECT id, spotify_id, name, artists, album, genre, duration_ms, popularity,
		        valence, energy, danceability, tempo, acousticness, instrumentalness, loudness, speechiness,
		        COALESCE(preview_url, '')
		 FROM tracks WHERE spotify_id = $1`, spotifyID)
	t, err := scanTrack(row)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	return t, err
}

// BulkInsert inserts tracks in batches of 1000 using multi-row INSERT …
// ON CONFLICT (spotify_id) DO NOTHING. Returns the number of rows inserted.
func (r *trackRepository) BulkInsert(ctx context.Context, tracks []*entity.Track) (int, error) {
	const batchSize = 1000
	totalInserted := 0

	for start := 0; start < len(tracks); start += batchSize {
		end := start + batchSize
		if end > len(tracks) {
			end = len(tracks)
		}
		batch := tracks[start:end]

		inserted, err := r.insertBatch(ctx, batch)
		if err != nil {
			return totalInserted, fmt.Errorf("insertBatch at offset %d: %w", start, err)
		}
		totalInserted += inserted
	}
	return totalInserted, nil
}

func (r *trackRepository) insertBatch(ctx context.Context, batch []*entity.Track) (int, error) {
	const cols = 15 // all columns except id (generated by DB)
	placeholders := make([]string, len(batch))
	args := make([]any, 0, len(batch)*cols)

	for i, t := range batch {
		base := i * cols
		placeholders[i] = fmt.Sprintf(
			"($%d,$%d,$%d,$%d,$%d,$%d,$%d,$%d,$%d,$%d,$%d,$%d,$%d,$%d,$%d)",
			base+1, base+2, base+3, base+4, base+5,
			base+6, base+7, base+8, base+9, base+10,
			base+11, base+12, base+13, base+14, base+15,
		)
		args = append(args,
			t.SpotifyID, t.Name, t.Artists, t.Album, t.Genre,
			t.DurationMS, t.Popularity,
			t.Valence, t.Energy, t.Danceability, t.Tempo,
			t.Acousticness, t.Instrumentalness, t.Loudness, t.Speechiness,
		)
	}

	query := `INSERT INTO tracks
		(spotify_id, name, artists, album, genre, duration_ms, popularity,
		 valence, energy, danceability, tempo, acousticness, instrumentalness, loudness, speechiness)
		VALUES ` + strings.Join(placeholders, ",") + `
		ON CONFLICT (spotify_id) DO NOTHING`

	tag, err := r.db.Exec(ctx, query, args...)
	if err != nil {
		return 0, err
	}
	return int(tag.RowsAffected()), nil
}

// GetCandidatesForMood returns popularity-filtered tracks ordered by popularity DESC.
// The mood parameter is available for future genre-based filtering — not used yet.
// TODO: consider filtering by genre affinity per mood (e.g., workout → electronic/hip-hop)
func (r *trackRepository) GetCandidatesForMood(ctx context.Context, _ entity.Mood, minPopularity int, limit int) ([]*entity.Track, error) {
	rows, err := r.db.Query(ctx,
		`SELECT id, spotify_id, name, artists, album, genre, duration_ms, popularity,
		        valence, energy, danceability, tempo, acousticness, instrumentalness, loudness, speechiness,
		        COALESCE(preview_url, '')
		 FROM tracks
		 WHERE popularity >= $1
		 ORDER BY popularity DESC
		 LIMIT $2`,
		minPopularity, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return collectTracks(rows)
}

// GetTopByFeatureProximity uses the idx_tracks_features index with a ±0.2 bounding
// box on (valence, energy, danceability) to narrow candidates cheaply.
// The usecase re-ranks results by exact 4D cosine similarity.
// Bounds are pre-computed in Go to avoid PostgreSQL "operator is not unique" errors
// that arise when arithmetic is performed on untyped query parameters.
func (r *trackRepository) GetTopByFeatureProximity(ctx context.Context, vector [4]float64, limit int) ([]*entity.Track, error) {
	const window = 0.2
	const minPopularity = 30

	v, e, d := vector[0], vector[1], vector[2]
	rows, err := r.db.Query(ctx,
		`SELECT id, spotify_id, name, artists, album, genre, duration_ms, popularity,
		        valence, energy, danceability, tempo, acousticness, instrumentalness, loudness, speechiness,
		        COALESCE(preview_url, '')
		 FROM tracks
		 WHERE popularity >= $1
		   AND valence      BETWEEN $2 AND $3
		   AND energy       BETWEEN $4 AND $5
		   AND danceability BETWEEN $6 AND $7
		 ORDER BY popularity DESC
		 LIMIT $8`,
		minPopularity,
		v-window, v+window,
		e-window, e+window,
		d-window, d+window,
		limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return collectTracks(rows)
}

// ── helpers ───────────────────────────────────────────────────────────────────

func scanTrack(row pgx.Row) (*entity.Track, error) {
	t := &entity.Track{}
	err := row.Scan(
		&t.ID, &t.SpotifyID, &t.Name, &t.Artists, &t.Album, &t.Genre,
		&t.DurationMS, &t.Popularity,
		&t.Valence, &t.Energy, &t.Danceability, &t.Tempo,
		&t.Acousticness, &t.Instrumentalness, &t.Loudness, &t.Speechiness,
		&t.PreviewURL,
	)
	if err != nil {
		return nil, err
	}
	return t, nil
}

func (r *trackRepository) GetTrending(ctx context.Context, limit int) ([]*entity.Track, error) {
	if limit <= 0 || limit > 100 {
		limit = 20
	}
	rows, err := r.db.Query(ctx,
		`SELECT id, spotify_id, name, artists, COALESCE(album,''), COALESCE(genre,''),
		        COALESCE(duration_ms,0), COALESCE(popularity,0),
		        COALESCE(valence,0), COALESCE(energy,0), COALESCE(danceability,0), COALESCE(tempo,0),
		        COALESCE(acousticness,0), COALESCE(instrumentalness,0), COALESCE(loudness,0), COALESCE(speechiness,0),
		        COALESCE(preview_url,'')
		 FROM tracks
		 WHERE popularity IS NOT NULL
		 ORDER BY popularity DESC
		 LIMIT $1`, limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return collectTracks(rows)
}

func collectTracks(rows pgx.Rows) ([]*entity.Track, error) {
	var tracks []*entity.Track
	for rows.Next() {
		t := &entity.Track{}
		if err := rows.Scan(
			&t.ID, &t.SpotifyID, &t.Name, &t.Artists, &t.Album, &t.Genre,
			&t.DurationMS, &t.Popularity,
			&t.Valence, &t.Energy, &t.Danceability, &t.Tempo,
			&t.Acousticness, &t.Instrumentalness, &t.Loudness, &t.Speechiness,
			&t.PreviewURL,
		); err != nil {
			return nil, err
		}
		tracks = append(tracks, t)
	}
	return tracks, rows.Err()
}
